name: 'Build Arkdep Images and Upload (Docker)'

on:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        edition: [arkanelinux, test-arkanelinux-kde]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

#    - name: Free up disk space
#      uses: jlumbroso/free-disk-space@main
#      with:
#        tool-cache: true
#        android: true
#        dotnet: true
#        haskell: true
#        large-packages: true
#        docker-images: false
#        swap-storage: true

    - name: Build inside ArchLinux container
      uses: addnab/docker-run-action@v3
      with:
        image: archlinux:latest
        options: --privileged -v ${{ github.workspace }}:/workspace
      run: |
        pacman -Sy --noconfirm base-devel git btrfs-progs arch-install-scripts
        cd /workspace
        git clone --depth 1 https://github.com/arkanelinux/arkdep.git
        install -m755 arkdep/arkdep /usr/bin/
        install -m755 arkdep/arkdep-build /usr/bin/
        git clone --depth 1 https://github.com/silverhadch/arkdep-variants.git arkdep-variants
        mkdir -p target
        cd arkdep-variants
        arkdep-build ${{ matrix.edition }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.edition }}-image
        path: target/*.tar.zst

    - name: Clean up old images
      run: |
        find target -name "*.tar.zst" -type f -mtime +7 -exec rm {} \;
